# Generated by Django 5.2 on 2025-04-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='cost_per_serving',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
